check:
  physics:

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for moving incorrectly"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  timer:

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging for a long period"

  heuristics:

    enabled: true

    confidence-thresholds:
      "!!":
        25:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!!) (heuristics)"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      "!":
        25: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (!) (heuristics)"
        50:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!) (heuristics)"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      "?!":
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (?!) (heuristics)"
        75: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously #2 (?!) (heuristics)"


  attackRaytrace:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (hitbox)"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (hitbox)"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  interactionRaytrace:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for interacting suspiciously"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  protocolScanner:

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for moving incorrectly"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  abilitySpeedLimiter:

    # nothing

filter:

  health: true

  enchantments: true

  chat-insults: true

  chat-spam: true

layout:

  verbose: "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})"

  notify: "{prefix} &c&lNotify&8: &7{text}"

  prefix: "&8[&c&lIntave&8]&7 "
